apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali${NAME_SUFFIX}
  labels:
    app: kiali
    version: ${VERSION_LABEL}
data:
  config.yaml: |
    server:
      port: 20001
      static_content_root_directory: /opt/kiali/console
      credentials:
        username: jdoe
        password: password
